spring:
  thymeleaf.cache: false
  sbp:
    enabled: true
    runtime-mode: development
    pluginsRoot: ../plugins
    classes-directories: "target/classes, target/resources"
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: INFO
    ROOT: debug